In [2]:
exec(open('ox_hl.py').read())

1/1 [==============================] - 0s 36ms/step


In [10]:
make_plays_model()
pq = empty_board.copy()
print(plays_model.predict(pq.reshape(1, 9, 2)))
add_o(pq, 1)
print(plays_model.predict(pq.reshape(1, 9, 2)))
add_x(pq, 4)
print(plays_model.predict(pq.reshape(1, 9, 2)))


1/1 [==============================] - 0s 27ms/step
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]]
1/1 [==============================] - 0s 50ms/step
[[1. 0. 1. 1. 1. 1. 1. 1. 1.]]
1/1 [==============================] - 0s 18ms/step
[[1. 0. 1. 1. 0. 1. 1. 1. 1.]]


In [13]:
scores, illegals = play_match(res_model_move, suggest_move)
print(f'Draws, wins for trained network, wins for perfect network: {scores}')
print(f'Illegal moves by trained network, illegal moves by perfect network: {illegals}')



Draws, wins for trained network, wins for perfect network: [97, 0, 3]
Illegal moves by trained network, illegal moves by perfect network: [3, 0]


In [12]:
scores, illegals

([95, 0, 5], [4, 0])